### ISSUE TITLE
Include the chime and voice WAV files

### ISSUE THREAD

**Issue by MrAureliusR** [p2pquake/eew-detector#1]
Hi there! Just stumbled across this project after doing some research on the EEW system in Japan. I'm interested in also decoding the FSK burst that gets sent to turn TVs on during a tsunami warning, but I'm also curious about giving this project a try.

Is it possible to add the WAV files in, or at least include links to a reliable source for them in the README?

Thanks!

**Comment by typewriter** [comment]
Thank you for your interest!

Unfortunately, we can't publish the chime and voice because NHK (Japan Broadcasting Corporation) owns the copyright.

However, only the chime can be detected with the chime sound provided on the NHK website (https://www.nhk.or.jp/sonae/bousai/about.html).

Hope this helps.

**Comment by MrAureliusR** [comment]
Okay, I've managed to get clean copies of both the chime, and the "kinkyu jishin sokuhodesu" parts.

What goes into baseFFTs.wav and what goes into baseAnnFFT3.wav?

**Comment by typewriter** [comment]
Set the chime sound to baseFFTs.wav and the voice to baseAnnFFT3.wav.

Please refer to the comments of the source code for the number of channels, number of bits, and sample rate of the WAVE file.
